<?php
declare(strict_types=1);

namespace ExCompass\Domain\Catalog;

final class VerticalDetailRepository
{
    public function find(string $slug): array
    {
        $all = $this->all();
        return $all[$slug] ?? $all['real-estate'];
    }

    public function all(): array
    {
        return [
            'real-estate'=>['singular'=>'Project','headline'=>'Top Residential Projects in Pune','subline'=>'Expertly evaluated residential projects for homebuyers and investors.','category_label'=>'Property Type','categories'=>['Apartment','Villa','Township'],'tier_label'=>'Budget','tiers'=>['Under ₹1 Cr','₹1–2 Cr','₹2 Cr+'],'status_label'=>'Possession','statuses'=>['Ready','2027','2028+'],'intent_label'=>'Best For','intents'=>['End Use','Investment','Family'],'score_labels'=>['Location & Connectivity','Developer Track Record','Planning & Amenities','Construction / Delivery','Price & Value','Social Infrastructure','Sustainability / Design']],
            'hospitals'=>['singular'=>'Hospital','headline'=>'Top Hospitals in Pune','subline'=>'Healthcare institutions assessed for clinical capability, access and patient experience.','category_label'=>'Specialty','categories'=>['Multi-speciality','Cardiac','Orthopaedic'],'tier_label'=>'Price Level','tiers'=>['Value','Mid-range','Premium'],'status_label'=>'Availability','statuses'=>['24x7','Emergency','Appointment'],'intent_label'=>'Best For','intents'=>['Families','Emergency','Specialist Care'],'score_labels'=>['Clinical Capability','Doctor Network','Emergency Readiness','Technology & Facilities','Patient Experience','Access & Connectivity','Transparency']],
            'schools'=>['singular'=>'School','headline'=>'Top Schools in Pune','subline'=>'School rankings built around academics, campus, student development and access.','category_label'=>'Board','categories'=>['CBSE','ICSE','IB / Cambridge'],'tier_label'=>'Fee Band','tiers'=>['Value','Mid-range','Premium'],'status_label'=>'Admissions','statuses'=>['Open','Waitlist','Upcoming'],'intent_label'=>'Best For','intents'=>['Academics','Sports','Holistic'],'score_labels'=>['Academic Outcomes','Faculty & Leadership','Campus & Safety','Co-curricular Depth','Value & Fees','Parent Experience','Access & Transport']],
            'restaurants'=>['singular'=>'Restaurant','headline'=>'Top Restaurants in Pune','subline'=>'Local dining picks scored for food, consistency, service, ambience and value.','category_label'=>'Cuisine','categories'=>['Indian','Asian','Global'],'tier_label'=>'Spend','tiers'=>['₹','₹₹','₹₹₹'],'status_label'=>'Service','statuses'=>['Dine-in','Delivery','Reservations'],'intent_label'=>'Best For','intents'=>['Family','Date Night','Groups'],'score_labels'=>['Food Quality','Consistency','Service','Ambience','Value','Location & Access','Distinctiveness']],
            'hotels'=>['singular'=>'Hotel','headline'=>'Top Hotels in Pune','subline'=>'Hotels evaluated for rooms, service, location, dining and business convenience.','category_label'=>'Hotel Type','categories'=>['Business','Luxury','Boutique'],'tier_label'=>'Price Band','tiers'=>['₹₹','₹₹₹','₹₹₹₹'],'status_label'=>'Booking','statuses'=>['Available','Popular','Advance Booking'],'intent_label'=>'Best For','intents'=>['Business','Staycation','Events'],'score_labels'=>['Room Quality','Service','Location','Dining','Business Facilities','Value','Guest Experience']],
            'colleges'=>['singular'=>'College','headline'=>'Top Colleges in Pune','subline'=>'Higher-education institutions compared on academics, outcomes and campus ecosystem.','category_label'=>'Stream','categories'=>['Engineering','Arts & Commerce','Management'],'tier_label'=>'Fee Band','tiers'=>['Value','Mid-range','Premium'],'status_label'=>'Admissions','statuses'=>['Open','Entrance','Upcoming'],'intent_label'=>'Best For','intents'=>['Placements','Research','Campus Life'],'score_labels'=>['Academic Reputation','Faculty','Placements','Research','Campus & Facilities','Value','Student Experience']],
            'malls'=>['singular'=>'Mall','headline'=>'Top Malls in Pune','subline'=>'Shopping destinations scored for retail mix, food, entertainment and convenience.','category_label'=>'Format','categories'=>['Regional Mall','Lifestyle Mall','Community Mall'],'tier_label'=>'Spend','tiers'=>['Value','Mixed','Premium'],'status_label'=>'Hours','statuses'=>['Open Daily','Late Hours','Weekend Peak'],'intent_label'=>'Best For','intents'=>['Shopping','Dining','Entertainment'],'score_labels'=>['Retail Mix','Dining','Entertainment','Access & Parking','Family Experience','Value','Design & Comfort']],
            'gyms'=>['singular'=>'Gym','headline'=>'Top Gyms in Pune','subline'=>'Fitness centres assessed for equipment, coaching, hygiene, programming and value.','category_label'=>'Format','categories'=>['Full Service','Functional','Boutique'],'tier_label'=>'Membership','tiers'=>['Value','Mid-range','Premium'],'status_label'=>'Access','statuses'=>['Daily','24x7','Class Based'],'intent_label'=>'Best For','intents'=>['Strength','Weight Loss','Group Fitness'],'score_labels'=>['Equipment','Coaching','Hygiene','Programming','Value','Access','Member Experience']],
            'salons'=>['singular'=>'Salon','headline'=>'Top Salons in Pune','subline'=>'Beauty and grooming destinations scored for service quality, hygiene and value.','category_label'=>'Type','categories'=>['Unisex','Women','Premium Studio'],'tier_label'=>'Spend','tiers'=>['₹','₹₹','₹₹₹'],'status_label'=>'Booking','statuses'=>['Walk-in','Appointment','Weekend Busy'],'intent_label'=>'Best For','intents'=>['Hair','Beauty','Grooming'],'score_labels'=>['Service Quality','Stylist Expertise','Hygiene','Product Quality','Value','Convenience','Client Experience']],
            'automotive'=>['singular'=>'Auto Centre','headline'=>'Top Automotive Centres in Pune','subline'=>'Dealers and service centres assessed for sales support, service quality and ownership experience.','category_label'=>'Type','categories'=>['Dealer','Service Centre','Multi-brand'],'tier_label'=>'Price Band','tiers'=>['Value','Mid-range','Premium'],'status_label'=>'Service','statuses'=>['Sales & Service','Service','Appointment'],'intent_label'=>'Best For','intents'=>['New Car','Service','Premium Cars'],'score_labels'=>['Sales Experience','Service Quality','Technical Capability','Transparency','Turnaround Time','Access','Owner Experience']],
            'coworking'=>['singular'=>'Coworking Space','headline'=>'Top Coworking Spaces in Pune','subline'=>'Flexible workspaces ranked for location, infrastructure, community and value.','category_label'=>'Workspace','categories'=>['Managed Office','Coworking','Enterprise'],'tier_label'=>'Price Band','tiers'=>['Value','Mid-range','Premium'],'status_label'=>'Availability','statuses'=>['Available','Limited','On Request'],'intent_label'=>'Best For','intents'=>['Startups','Teams','Enterprise'],'score_labels'=>['Location','Workspace Quality','Internet & Infrastructure','Meeting Facilities','Community','Value','Flexibility']],
            'localities'=>['singular'=>'Locality','headline'=>'Best Places to Live in Pune','subline'=>'Neighbourhood intelligence combining connectivity, schools, healthcare, lifestyle and affordability.','category_label'=>'Area Type','categories'=>['IT Corridor','Established','Emerging'],'tier_label'=>'Affordability','tiers'=>['Value','Balanced','Premium'],'status_label'=>'Growth','statuses'=>['Established','Growing','Fast Growing'],'intent_label'=>'Best For','intents'=>['Families','Professionals','Investors'],'score_labels'=>['Connectivity','Schools','Healthcare','Restaurants & Retail','Safety & Comfort','Green Space','Affordability']],
            'preschools'=>['singular'=>'Preschool','headline'=>'Top Preschools in Pune','subline'=>'Early-learning centres compared on teaching approach, safety, facilities and parent experience.','category_label'=>'Programme','categories'=>['Playgroup','Montessori','Daycare + Preschool'],'tier_label'=>'Fee Band','tiers'=>['Value','Mid-range','Premium'],'status_label'=>'Admissions','statuses'=>['Open','Limited','Waitlist'],'intent_label'=>'Best For','intents'=>['Play-based','Montessori','Daycare'],'score_labels'=>['Learning Approach','Teacher Quality','Safety','Facilities','Parent Communication','Value','Convenience']],
            'doctors'=>['singular'=>'Doctor','headline'=>'Top Doctors & Specialists in Pune','subline'=>'A structured discovery experience for specialist profiles; editorial scores are demo placeholders until verified.','category_label'=>'Specialty','categories'=>['Cardiology','Orthopaedics','Dermatology'],'tier_label'=>'Consultation','tiers'=>['Value','Mid-range','Premium'],'status_label'=>'Availability','statuses'=>['Today','This Week','Appointment'],'intent_label'=>'Best For','intents'=>['Consultation','Second Opinion','Ongoing Care'],'score_labels'=>['Qualifications','Experience','Clinical Focus','Patient Communication','Hospital Access','Availability','Transparency']],
            'banquets'=>['singular'=>'Banquet','headline'=>'Top Banquet & Event Venues in Pune','subline'=>'Venues compared for capacity, service, location, food and event execution.','category_label'=>'Venue Type','categories'=>['Hotel Ballroom','Resort','Banquet Hall'],'tier_label'=>'Spend','tiers'=>['₹₹','₹₹₹','₹₹₹₹'],'status_label'=>'Booking','statuses'=>['Available','Popular','Advance Booking'],'intent_label'=>'Best For','intents'=>['Weddings','Corporate','Social Events'],'score_labels'=>['Venue Quality','Food & Catering','Service','Location','Capacity & Flexibility','Value','Event Experience']],
            'cafes'=>['singular'=>'Café','headline'=>'Top Cafés in Pune','subline'=>'Cafés scored for coffee, food, ambience, work-friendliness and value.','category_label'=>'Style','categories'=>['Specialty Coffee','All-day Café','Bakery Café'],'tier_label'=>'Spend','tiers'=>['₹','₹₹','₹₹₹'],'status_label'=>'Access','statuses'=>['Walk-in','Reservations','Weekend Busy'],'intent_label'=>'Best For','intents'=>['Work','Dates','Friends'],'score_labels'=>['Coffee & Drinks','Food','Ambience','Service','Work Friendliness','Value','Location']],
            'weekend'=>['singular'=>'Destination','headline'=>'Top Weekend Getaways from Pune','subline'=>'Short escapes ranked for experience, access, stay options, value and seasonality.','category_label'=>'Trip Type','categories'=>['Nature','Heritage','Lake / Resort'],'tier_label'=>'Budget','tiers'=>['Value','Mid-range','Premium'],'status_label'=>'Season','statuses'=>['All Season','Monsoon','Winter'],'intent_label'=>'Best For','intents'=>['Families','Friends','Couples'],'score_labels'=>['Experience','Travel Time','Stay Options','Food & Facilities','Value','Safety & Comfort','Seasonal Appeal']],
        ];
    }
}
